server:
  port: 8761

eureka:
  instance:
    hostname: registry
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@eurakaBackOne:8762/eureka/

security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
